---

- name: Ensure Sentry is stopped
  supervisorctl: name={{item}} state=stopped
  with_items:
    - sentry-web
    - sentry-worker
    - sentry-cron

- name: Remove Supervisor configuration
  file: path={{supervisor_incdir}}/sentry.conf state=absent
